### ISSUE TITLE
aloulou ya kessa7

### ISSUE THREAD

**Issue by ghassen-fatnassi** [SEPPUK/Algorithms#1]
kessa7 sayed ala
btw , your implementation of trees , try implementing it like a graph (adjacency list) ,you will feel it will become cleaner 
with love <3

**Comment by SEPPUK** [comment]
Yeah, this code is definitely not the best, I did it last year as a quick implementation of algorithms seen in class, right before getting into graphs. The challenge was to stick only to stack and queue. Obviously there is room for improvement when implementing graphs related techniques. Maybe one day I'll add the code on a separate file, if I ever found the time 😆.
Thanks for the insight GASS, Love.
